### PR TITLE
Gestion valeur générées en BD

### LINKED ISSUE #10: DB default values
We have a table with a default value defined on the primary key column:

image

When inserting a new object, nothing is added to the historisation table, because the `nextval(...)` instruction is passed as text and it should be passed as an instruction (or not passed at all, because then the DB will use the default value).

image

When updating, nothing is added to the historisation table, because it triggers again the same error:

image

The same behavior is observed using also other default values, see also #7

### PR DESCRIPTION
**Pull request by arx-it**

### CODE REVIEW

**Comment by kalbermattenm** [comment]
@maltaesousa , same here?

**Review by maltaesousa — CHANGES_REQUESTED** [review]
Still having the issue.

Steps to reproduce:

1. Create a Polygon table with a `serial` type column and a `uuid` type column
2. Edit the `uuid` type column and add a default value to `uuid_generate_v4()`
3. Open qgis, historize the table and draw a new feature
4. Save the new feature and validate the SITN4D dialog-> In PostGIS message panel, there's a warning message:

```
2021-06-30T12:29:50     WARNING    ATTENTION: ATTENTION: aucune transaction en cours
2021-06-30T12:35:56     WARNING    Requête : DEALLOCATE addfeatures a retourné 7 [ERREUR: l'instruction préparée « addfeatures » n'existe pas
             ]
```

The full message on PostgreSQL logs:

```
2021-06-30 12:35:56.446 CEST [29508] ERREUR:  syntaxe en entrée invalide pour le type uuid : « uuid_generate_v4() » au caractère 584
2021-06-30 12:35:56.446 CEST [29508] INSTRUCTION :  INSERT INTO "amenagement"."at700_surfaces_assolement_h"("geom","id","idobj","start_date","end_date","start_event_id","end_event_id") VALUES (st_multi(st_geomfromwkb($1::bytea,2056)),1099,'uuid_generate_v4()','2021-06-30T12:35:56.440',NULL,10,NULL) RETURNING "histo_id"
2021-06-30 12:35:56.447 CEST [29508] ERREUR:  l'instruction préparée « addfeatures » n'existe pas
2021-06-30 12:35:56.447 CEST [29508] INSTRUCTION :  DEALLOCATE addfeatures
2021-06-30 12:35:56.448 CEST [29508] ATTENTION:  aucune transaction en cours
```

Editing the same layer without plugin doesn't generate errors.

**Comment by arx-it** [comment]
I see, it works for the primary key column (serial or uuid), bot not for the other ones. I'll check

**Comment by arx-it** [comment]
I pushed the fix to the branch #10

**Comment by arx-it** [comment]
Should be properly fixed now

**Review by maltaesousa — APPROVED** [review]
Works great! Thanks a lot!

**Pull request merged**
